modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/DDX5/MCSM/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://api.modrinth.com/updates/mcsm/forge_updates.json?neoforge=only"
displayURL="https://github.com/DDX5/MCSM"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
